package BACK.PREDEF;

public enum typeObjet {

    MUR,VIDE,PORTE,PACMAN,FANTOME_BLEU,FANTOME_ROUGE,FANTOME_VERT,FANTOME_ROSE,PETIT_BONBON,GROS_BONBON,CERISE,FRAISE,RAISIN,POMME,ORANGE,BANANE,POIRE,TELEPORT
}
